### PR TITLE
Modify examples according to #372

### PR DESCRIPTION
**Pull request by fededonna**
according to #372

### CODE REVIEW

**Comment by sichvoge** [comment]
I pull in @usarid and @petrochenko-pavel-a to confirm what the default value for an empty annotation actually is. I can see use cases where you don't want to have a value, but rather just the annotation.

The initial case was that the example still used `parameters`, but @fededonna also outline that values for an annotations should not be empty since it creates it with `null`.

**Comment by usarid** [comment]
Annotations can certainly be specified with no values if desired. What's wrong with `null`?

**Comment by usarid** [comment]
We'll probably do something along the lines of https://github.com/raml-org/raml-spec/issues/394 now, to add a `null` type and therefore allow us to have valueless annotations after all.

@sichvoge in this case we can set the annotation type of `experimental` and `feedbackRequested` to be `null` in which case that's the only value they can take. Or you can set one to be `null` and the other `null | string` to illustrate some options. Your call.

**Comment by sichvoge** [comment]
OK, I'll wait for discussion on #394 to be finished before changing it.

**Comment by sichvoge** [comment]
Fixed issues in PR #409. This PR will no longer be merged, but leave it open bc there is still an open discussion.

**Comment by sichvoge** [comment]
Closing that PR and create a new one when #409 is done!

**Pull request closed without merging**
