### PR TITLE
introduces new overloading section

### PR DESCRIPTION
**Pull request by sichvoge**
According to #184 we need to explicitly define how a RAML processor should act in certain cases where one overloads, for example, a resource or method. This section gives an overview about the rules that are mentioned in #184.

### CODE REVIEW

**Comment by usarid** [comment]
I proposed largely eliminating overloading altogether in #184 so we need to get closure on that before finalizing this PR. How can we get comfort around that?

**Comment by sichvoge** [comment]
Guess we need to answer final questions on the issue first. Do you really want to remove it completely or are we providing at least some kind of information around ambiguity and how to detect them?

**Comment by usarid** [comment]
Once we resolve #184 we'll see whether there's anything left to say in this section, vs just specifying the rule in the section for resources.

**Comment by sichvoge** [comment]
Agree; I don't think that the section is necessary if we only go for the resources. Everything else is not allowed due to the YAML nature and unique keys.

**Comment by usarid** [comment]
OK, so given my last statement about not having overloading, we should not have this section, so I can't accept this PR which introduces this section.

**Pull request closed without merging**
